### ISSUE TITLE
As LD engineer I need to experiment with the use of subproperties for querying Person and Place information

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#29]
The aim of this issue is to evaluate the use of isSubPropertyOf in queries to find all Person (or Place) information about a programme in one query. As all person-related properties (e.g. hasSpeaker, hasCrew) inherit from the same property, it should be possible to specify in the query that we want to find all objects that are linked to the programme by a subproperty of that property, thereby getting all persons related to the programme in one go. The same goes for Place information. The question is whether this works as expected, and what the performance is.

## Tasks
- [x] load NISV schema into the triple store, so the relations/properties can be queried
- [x] write queries that use the subPropertyOf information
- [x] inspect the query results and report
- [ ] compare difference between reconciled persons/places & "blank node situation"

## Acceptance criteria:
- [ ] It is clear whether the query works or not, and how long it takes to run

## Background
In the Sound and Vision archive, we have multiple properties that indicate the involvement of a Person (producer, creator, speaker etc.) and also multiple properties that indicate the involvement of a Place (recordingLocation, location etc.). We want to query these in one go - give me all the Persons involved in this programme, or all the Places. In the RDF schema, we have grouped these properties together under a property that describes the involvement of a person - hasEntityInRole, and a property that describes the involvement of a place - hasLocation. Now, we need a means of using this information to enable easy querying of the data.

One option is to use the subproperty relation explicitly in the query. That will be investigated in this story. The option of using inferencing will be investigated in another story (#47), as will the option of leaving the property unspecified and using the object type instead (#71). A fourth option is to map the data to explicitly add the high-level relations to the data.

**Comment by jblom** [comment]
@mwigham @wmelder could you provide some examples in the description? This makes the purpose easier to understand

**Comment by mwigham** [comment]
This will need to wait until we have the next version of the data; at present we don't have all the person objects correctly mapped.

**Comment by jblom** [comment]
@wmelder @mwigham can you please update & split this up into simpler issues (with nice examples)

**Comment by mwigham** [comment]
I've tried to make this more focused on the aim - be able to query all Person relations in one go - and have split the different possible methods into 2 stories (the third possibility, of mapping the data, I have not turned into a story as I would regard that as more a last-ditch solution)
@wmelder Your interpretation of this story had more to do with using other schemas. Mapping to other schemas is discussed in #15 (and #5, we need to look at those two issues more closely). We also have the issue of actually reusing ideas from other schemas in our own schema, that is currently only listed in the epic #7 and can be worked out as a story at some point.

**Comment by jblom** [comment]
@mwigham please check the description and make it a bit more short & sweet so we all can understand what this work entails in a glance

**Comment by wmelder** [comment]
I have already found the way to query the triple store to realize this... Now I need to relate that query more to this issue and report on it.

**Comment by roelandordelman** [comment]
@wmelder this one is in done but acceptance criteria are still unchecked. I prepared this text for the release notes: 

- We are working on preparing the data and infrastructure to make it possible to use **Linked Data** concepts within the Media Suite and the CLARIAH infrastructure. The past weeks we have been evaluating querying the NISV data using  properties related to the involvement of Persons (producer, creator, speaker etc.) and Places (recordingLocation, location etc.)   

I would like to report an outcome here, e.g. by putting "succesfully" before "evaluating". Note that release notes should be very brief but of course, should make sense.. ;)
