### ISSUE TITLE
As a schema user and provider, I want the schema to be available in a HTML representation

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#31]
This should show the schema in a simple way, with decent styling. Editing should also be possible. This issue is a result of a comment in https://github.com/beeldengeluid/beng-lod-server/issues/10

**Acceptance criteria**
- [ ] basically turn [this](http://data.rdlabs.beeldengeluid.nl/schema) into [this](https://schema.org/AudioObject)
- [ ] the HTML markup should contain RDFa attributes (see [this](https://schema.org/docs/schema_org_rdfa.html) as an example schema in RDFa)
- [ ] don't use Javascript, just HTML & CSS
- [ ] think about how to make the schema "clickable" so you can view individual classes & properties in separate views. Then create an issue for that
- [ ] think about other visual representations of the schema

**Comment by mwigham** [comment]
We need to discuss the extent to which editing should be possible in the HTML representation, and how that would work in conjunction with possible other editing methods

**Comment by jblom** [comment]
@mwigham thanks for reporting this one. We'll have to finetune it in the backlog later on (also with @wmelder )

**Comment by wmelder** [comment]
for inspiration look at the way DCMI and schema.org are publishing their data models...

**Comment by wmelder** [comment]
no editing should be possible... it is a document for consultation only, not editing.
editing the schema should be done in a text editor, representation as HTML should be generated automatically, so it can be consumed by humans ..

**Comment by wmelder** [comment]
@avlisodraude check this out. This is an out-of-the-box ontology representation in HTML. Took me 5 minutes to produce.
http://lambdamusic.github.io/Ontospy/

**Comment by avlisodraude** [comment]
@jblom @mwigham 

Issue for beng-lod-server done in branch:
_issue/#31-html-beng-schema-representation_

### What been done?
An HTML representation of BenG Schema has been added to the project which allows:
- To view every Class in a table with their respective elements (when available) like Class name subClassOf (parent Class) and a description for the class. (**screenshot 1**)
- The interface allows the user to switch between available languages (en, nl) and also allows whoever is in charge of editing the Schema to detect and hence made the corresponding changes to the Schema.
- Every Class and subClassOf is clickable which will result in displaying in 2 actions based on the nature of the Class (BenG or external Class). This actions are:  
    - Redirecting the user to the external source (opening in a new tab/window)
    - Opening the BenG Class in a new table with its corresponding Properties and similar options as in the Classes table. 
- When in a specific Class table we face 2 possible views: 
    - A fully implemented class with all its properties in display (AudioVisualObject, **screenshot 2**)
    - An Abstract Class. In this case a message to the user is displayed letting her/him know that this class has no 'own properties' and a table shows (when available) with a list of the Classes this Abstract class is used to extend plus a row when the Class is the range of (**screenshot 3**).

### Issues detected
Some nodes containing text (comments, labels, descriptions,..) present inconsistencies in terms of providing no language specific text which based in this implementation means that the text will be skipped when rendering, as in the case of:
```
"http://www.w3.org/2000/01/rdf-schema#label":[
      {
        "@value":"has cast"
      },
      {
        "@value":"heeft cast",
        "@language":"nl"
      }
    ]
  }
```

### TODO
At the moment the Schema is loaded from a JSON representation located in the resources folder (locally). It would be ideal to load it from the schema url instead. Unfortunately the Schema (http://data.rdlabs.beeldengeluid.nl/schema) is not openly accessibly (only at B&G or with VNP on).

The Abstract classes might required some more work in terms of a more accurate representation of their meaning to the user.
Layout and eventually more functionality could be added later.

### Screenshots
1. Classes view
![Screenshot 2019-08-28 at 10.32.57.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/1ea125c9-97b2-4b43-8096-7f1f7b6e809f)

---
2. Class specific view

![Screenshot 2019-08-28 at 10.50.55.png]
(https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/2db4cdc6-52ed-445a-b613-e5d40638f27b)

---
3. Abstract Class
![Screenshot 2019-08-28 at 10.58.41.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/d11ebf72-fec0-4de4-a24c-2aa673d6cc75)

**Comment by mwigham** [comment]
@avlisodraude is it helpful if I review this? If so, could you write a test plan please?

**Comment by avlisodraude** [comment]
**@wmelder** 

Issues found during review have been solved, these issues where:

- Calling schema.html without / returned 404
- Langueges where not set properly if non selected

### Pull request
- https://github.com/beeldengeluid/beng-lod-server/pull/58

**Comment by wmelder** [comment]
@avlisodraude ready to close this issue.

A [new issue ](https://github.com/beeldengeluid/beng-lod-server/issues/60) was created including the remaining task to load the HTML from the latest version of the Turtle schema.
