### ISSUE TITLE
As a developer, I need to refine and publish the NISV RDF schema

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#4]
This issue builds on the initial model created in https://github.com/beeldengeluid/beng-lod-server/issues/3.  This model must be improved so it is suitable for publishing

# Tasks
- Specify explicitly which fields are attached to what GTAA controlled vocabulary ConceptScheme.
- Include field/resource type definitions.
- Look into possible ambiguity of the model. How to represent known rules to handle data amibuity (like genre information on several levels, or multiple titles)?
- Integrate user friendly labels for NISV metadata and for this use the list of field descriptions (created by Eva and Liliana).
- Take into consideration data modelling work being done within Sound and Vision (DAAN).
- Review the model with an RDF expert and with an archive expert
- Publish/register the designed model.
- Re-generate the internal test Linked Data set (for a sample of the archive) with the new model (not yet officially publishing the whole catalogue as LD, this requires more work)

# Products
- [ ] Publish data model on the beeldengeluid.nl domain (data.beeldengeluid.nl/schema??)

# Acceptance criteria
- [ ] Review by an RDF expert (such as Victor).
- [ ] Review by an archive expert (such as Tim).

**Comment by jblom** [comment]
@wmelder @mwigham this issue is probably outdated (if so please close)

**Comment by mwigham** [comment]
@jblom no, this is still one for the future. At some point we'll publish our schema and then it needs to be reviewed

**Comment by jblom** [comment]
@mwigham ok clear, keeping it and moving it to the top of the icebox
