### ISSUE TITLE
EPIC: Use Linked data to enable cross-collection searching in the Media Suite

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#40]
Many of the potential uses for linked data that are interesting for scholars involve searching across various collections in the Media Suite. 

Some of the tasks required to realise this epic are:

- [ ]  Develop a central 'Clariah' schema for the structure of the data, that is optimised for the use cases of the Media Suite (reusing existing schemas where possible, e.g. CIDOC, schema.org etc. The work of the annotation group can be useful here)
- [ ] Map the data fields for each collection to this schema
- [ ] Use the mappings to publish each collection as linked data in this schema (NB: for collections that are already available as linked data, we can look at whether to convert their data, or use reasoning or similar to include the data)
- [ ] Align domain ontologies (e.g. Brinkman and GTAA)
