### ISSUE TITLE
As a test user, I want the grlc api and linked data notebook to show role information

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#44]
Liliana indicated that Clariah scholars find it very important to see how a person is linked to an item. This information is currently missing from the grlc api and test notebook. 

Use case is to be able to start at a programme, see which people are present in which role, and then find 1) other programmes where they have the same role and 2) other programmes in which they have a different role. E.g. Pim Fortuyn speaks in the programme, other programmes where he speaks, other programmes where he is discussed

## Tasks
- [x] Adapt the person queries to handle the new EntityInRole structure
- [x] Adapt the queries and grlc API to include role information
- [x] Adapt the notebook to display the role information
- [ ] Review with Liliana to develop further requirements and criteria for how linked data should be shown

## Acceptance criteria
- [x] Correct role information is shown for all people and organisations
- [x] We can use the new APIs and notebooks to better specify the requirements for linked data

**Comment by jblom** [comment]
@mwigham @lilimelgar a nice issue. Moved this to the backlog

**Comment by mwigham** [comment]
First we need to make grlc accessible in the test version of the labs-search-api; although the code is present in master, the API section for grlc does not appear.

**Comment by mwigham** [comment]
The queries have been adapted to the new hasEntityInRole structure, so that all possible properties (creator, guest, speaker etc.) can be retrieved at once. This results in a big hit in performance. For example, retrieving programs for a person takes more than a minute. Splitting the request up into two queries, one to get all properties, and then a second to get all persons related with each of the properties does not appear to give any speed improvement. 

The biggest problem is with the getPersonsRelatedToPersons query, which now gives a server error. Splitting this one up into two parts, the first to retrieve all programs for the person, then the second to get all persons related to the programs, does result in a completed query, but it takes 12 minutes to find the persons related to Paul Verhoeven. 

There are clearly performance issues here that need to be tackled, this falls outside the scope of this issue.

**Comment by mwigham** [comment]
The current queries do not pick up personnames, as these use the relation 'hasEntityInRole'. and we search for relations that are subproperties of 'hasEntityInRole'. We need to consider whether we fix this in the query or in the schema.

**Comment by mwigham** [comment]
The queries work (with the exception of the issues noted above). Note: role names are returned in both languages, I have left it like this for now so that the client can choose and filter, later we can change this if we want. As Liliana is sadly no longer around for evaluation, I suggest we save that step for when we use this functionality in a test app.

**Comment by jblom** [comment]
@mwigham closed this one and your last comment gave me the idea that it might be useful to create a kind of simple index, on a web page, that shows an overview of all your notebooks with a title and short summary of what they do. Heck it might be even indexed as a separate collection in the media suite, so we can search for it ;-)

Just to spark your imagination on this one. 

Mainly this comes from myself not having a convenient overview of what you've already done (and I know it's a lot). Also I really think with such a page or whatever there is much more chance we can identify work that we can start using in the media suite.

**Comment by mwigham** [comment]
@jblom for internal or external use? If internal, then I can put them on the labs-notebooks wiki, with a link from the x-omgeving wiki if that is helpful. I can also beef up the brief descriptions currently in the repository README. However, as some notebooks that may be useful (for reference, not for reuse) are not checked in there, then that might be too limited.

**Comment by mwigham** [comment]
@jblom I've made this [wiki page](https://github.com/beeldengeluid/labs-notebooks/wiki) a central point for the notebooks. It lists the locations of notebooks, describes briefly what they do, and links to more details where appropriate

**Comment by jblom** [comment]
@mwigham this is a nice notebook hub, thanks. When we are farther with a means to provide access we can use this overview as a basis for building a nice HTML page dedicated to notebooks (e.g. as part of the labs.beeldengeluid.nl site)

@roelandordelman ping (just dropping an idea here)
