### ISSUE TITLE
As a developer, I need to link the NISV RDF model to other schemas

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#5]
Such as: EBU core: https://tech.ebu.ch/MetadataEbuCore, schema.org (e.g. https://schema.org/BroadcastEvent), IPTC or other?

**Tasks**
- [ ] Consult with other parties with interesting data as to which schemas are useful 
- [ ] Select a subset of schemas that have the highest priority for linking 
- [ ] Determine how best to link the NISV schema to these schemas (owl:sameAs?, BBC core:sameAs? subproperties?, skos matches, our own property (as at the BBC, allows us to use the sameAs concept without needing owl or being restricted to the owl definition)...?)
- [ ] Create a mapping between the NISV schema and these schemas
- [ ] Determine where to store this mapping
- [ ] Publish the mapping
- [ ] Decide how we will use this mapping to facilitate access to the NISV data (I expect this will generate a new issue to implement the result)

**Products**
- Mapping(s) between the NISV schema and the selected other schema(s)

**Acceptance criteria**
- [ ] Mapping is discussed with domain experts - perhaps in the LD discussion with NA, KB, etc?
- [ ] Describe the rational & decision making progress in the wiki of the beng-lod-server repo

**Comment by mwigham** [comment]
Initial overview of available ontologies here https://docs.google.com/document/d/1I9XRgPhyO_b-HbLGKrRjgQahEsc4F35yj7h1iPFaBco/edit?usp=sharing

**Comment by wmelder** [comment]
I think this can be closed.

We mapped to schema.org. Whenever we need to we can map to any other model, using the beng-lod-server solution.

for now, there is no need to map to other schemas. We can do this whenever a proper use case presents itself.
