### ISSUE TITLE
As a developer, I want to test creating triples from the DAAN backbone importer

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#50]
Currently, we import our Linked Data from OAI. Since the dawn of the new backbone, which pushes DAAN data to registered importers, we are able to get our hands on up-to-date B&G catalogue data as well. We will investigate both this option and the OAI option as part of our investigations into possible [LOD pipelines](https://github.com/beeldengeluid/beng-lod-server/wiki/LOD-pipeline)

**Tasks**
- [x] Extend the existing backbone importer, so it creates triples for unaggregated database items 
- [x] Create a mapping to convert DAAN metadata to linked data, make sure to align it with #13 
- [x] make sure to register a new instance to test running the importer (e.g. ask @jblom 
 to create backbone-lod.rdlabs.beeldengeluid.nl), so it can be registered to the pusher separately ([see the flex datastore pusher admin interface](http://dev-app-bng-01.beeldengeluid.nl:8101/))
- [x] Write the triples to Turtle (.ttl) files

**Acceptance criteria**
- Unit tests are passed for creating triples for series, seasons, programmes and clips
- The generated triples are in accordance with the NISV schema
- The importer can run for a day without crashing (time period may change, we need a time period that is sufficient for testing but doesn't generate unmanageable amounts of data)

The triples will NOT be loaded to a triplestore, that is a separate step in the pipeline that Willem Melder is already developing.

**Comment by jblom** [comment]
@mwigham I rewrote the approach, since it is not desirable to directly link with the flex data store. We should simply extend the importer and work from there. It is wise to register a separate importer, so the looooooooong process of the ES aggregation won't be stopped all the time ;-)

**Comment by mwigham** [comment]
From the task list:
"ask @jblom
to create backbone-lod.rdlabs.beeldengeluid.nl), so it can be registered to the pusher separately"
@jblom, could you create this please? No rush, as I will continue with other issues in the meantime.

**Comment by mwigham** [comment]
As the backbone importer doesn't allow for access to specific resources, I also created a version of the beng-lod-server that works on the Storage API. This has been tested on the dev version of the storage api as this is all that is currently available. As a result, the resources that are accessible are limited, here are some test resources that ar available:
ITEM 2101708190021663421
ITEM 2101701110009536021
PROGRAM 2101811120032795531
PROGRAM 2101606230008608731

**Comment by mwigham** [comment]
Small things to tidy up in later issues:

- Handle the situation nicely where an item has already been deleted (now get an error because the file already exists in the 'deleted' folder
- Change the code so that folders are only created once you write a file there - now have empty folders because the folders are immediately created when the storagelocation path is constructed, whereas we sometimes only want to construct the storagelocation path to check if it exists yet

**Comment by mwigham** [comment]
Ran the importer for more than 12 hours without any crashes.

@johannes could you review the importer please? Test plan is:
- [ ] Switch on the RDF backbone importer on http://dev-app-bng-01.beeldengeluid.nl:8101/, and let it run for an hour, then stop it
- [ ] On gustavgraves, go to /home/labs/backbone_lod/src
- [ ] check error_log.log to see if any errors occurred in the hour. The error 'file exists' followed by 'internal server error' for a delete is already known, please report any other errors.
- [ ] check success_log.log to see if calls were successfully handled
- [ ] take a couple of IDs from the success log, and see if you can find a corresponding file for that ID. If the action was POST, then go to daan_rdf_2101, and then choose a subfolder based on the ID each time (the directory structure is the ID split up into groups of 3 digits) until you reach the last folder. Check that there is a file <<ID>ID>.ttl in that folder and that it contains data. If the action was DELETE, start at daan_rdf_deleted_2101 and follow the same procedure. The file you find should be empty in this case.

@wmelder can you review the beng-lod-server please?
- [ ] check out the daan-storage-api-to-rdf branch
- [ ] run the server
- [ ] test it with the examples listed above. (Note: the levels are the DAAN levels (e.g. carrier is ITEM). We will need to decide which naming convention we choose for the final version)
-

**Comment by jblom** [comment]
@jwassenaarbg and @wmelder could you please finish the review for @mwigham ?

**Comment by wmelder** [comment]
@mwigham could you please merge the branch with master? There has been an update with flask-restx on master and the local merge with master gives me too many errors..

**Comment by wmelder** [comment]
@mwigham It seems I can run the server from within Pycharm, although it doesn't pass the unittests on commit. So, I think I can continue testing.

**Comment by mwigham** [comment]
Ok. I'm trying to fix the unit tests, but there is something up with the
application settings, I'm not sure where the application is loading them
from, but they're not the right ones :(

Op do 12 mrt. 2020 om 16:18 schreef Willem Melder <notifications@github.com

**Comment by wmelder** [comment]
application settings are loaded from settings-example.py. Therefor these settings need to be updated.

**Comment by wmelder** [comment]
@mwigham 
`STORAGE_BASE_URL = 'http://acc-app-bng-01.beeldengeluid.nl:8101'` toegevoegd aan settings. 
Alle voorbeelden geven een internal server error en een foutmelding:
`urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by mwigham** [comment]
I have fixed various bugs due to paths using '/' as a separator, and
differences in format between OAI-PMH and the Storage API. We will need to
later look at how we can better separate the code for these two methods, if
we continue to use both. I have checked this in, this should now run fine,
let me know otherwise please

Op vr 13 mrt. 2020 om 13:43 schreef Willem Melder <notifications@github.com

**Comment by wmelder** [comment]
still get errors... I tried to use curl on the command line, but the same...
here is the error log...
[response_1584104868826.txt](https://github.com/beeldengeluid/beng-lod-server/files/4329773/response_1584104868826.txt)

**Comment by mwigham** [comment]
@wmelder I've fixed the unit tests and checked the code in again, could you try again to run it please?

**Comment by wmelder** [comment]
@mwigham I pulled ans started the server locally.
again it fails...
127.0.0.1 - - [20/Mar/2020 16:45:45] "GET /resource/ITEM/2101708190021663421 HTTP/1.1" 500 -
then from the stack trace , urllib.error.HTTPError: HTTP Error 404: Not Found

what is wrong?

**Comment by jwassenaarbg** [comment]
Are you sure the mocking works as expected? Because normally you shouldn't do the actual calls and an HTTP error looks like it tried to do something

**Comment by wmelder** [comment]
The beng-lod server does look up the URL for the resource, but in the storage API.
Maybe the id for the example programs is not in the data? I tried Studio, but could find the item. Doesn't anything though, but if it really does not exist, then maybe even the response 404 is actually correct... Could anyone check the examples?

**Comment by mwigham** [comment]
@wmelder The examples do indeed not exist any more, which is a pain... Here are some new ones:
PROGRAM 2102003230266000731
ITEM 2102003230802977821
PROGRAM 2102003260266088931
ITEM 2102003260803448721

I have also changed the code to give a nicer response when a concept does not exist, could you please test this too?

**Comment by wmelder** [comment]
@mwigham All PROGRAMS and ITEM URI's return data. 🥂 

* Noticed that rendering the programs was not really fast (not slow either). Maybe we can time the pipeline to find out how much time is spent where.
* The items don't have a @graph element (could be that it is still valid without, when only one resource is in the data).
* I was wondering how to find out whether proper (non-)GTAA URI's are provided. I couldn't see any, so I did try the season that the first program belonged to: 
SEASON 2101901120252876331
It has a title value `Rail Away` that is an entry in the thesaurus: `http://data.beeldengeluid.nl/nongtaa/1692852`
The beng-lod data doesn't provide this ID. Can we get it from the DAAN data? The same question for the Series the season belongs to: SERIES 2101608030021705231
* I tried a program I found with the Media Suite: `http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/resource-viewer?id=509009@program&cid=nisv-catalogue-aggr&st=SARS%20virussen` could locate the audio `https://studio.mam.beeldengeluid.nl/studio/#ItemPlace:2101610020438186421` being part of this program in DAAN with this identifier: `PROGRAM PGM509009`. The beng-lod data is available using this `ITEM  2101610020438186421`. I could only see this identifier in the address bar. Is this the only location where it can be found? The program does not return data. You know why? Wrong identifier?

**Comment by mwigham** [comment]
@wmelder that's good news, thanks for testing. Regarding your other feedback:
- The performance has taken a serious knock from being done at a distance via VPNs, it is much faster onsite at beng
- I don't have experience with @graph elements, if we need that then we can discuss how to add it
- Title is currently not modelled as a SKOS concept in the schema, that is why the season title ends up being a blank node. We can add an issue to address this
- Yes, that is the wrong identifier. That is a site_id. For the storage API you need the normal id. Annoyingly, this isn't easily available in Studio, but you can find it by opening the carrier and then looking at the ID that is in the URL, in this case https://studio.mam.beeldengeluid.nl/studio/#CollectionPlace:%7B%22i%22:false,%20%22id%22:%222101608090075250931%22%7D. So if you use 2101608090075250931 in the API then it works

**Comment by mwigham** [comment]
@wmelder can this issue be closed?

**Comment by wmelder** [comment]
@mwigham Yes, I think you can close this issue (or at least put the status to done). 
The only thing I am not sure about is the JSON-LD without @graph, but since you use rdflib to serialize I guess it will be fine. See [here](https://w3c.github.io/json-ld-syntax/#json-ld-grammar) for some more information on the graph element.

**Comment by mwigham** [comment]
@wmelder Thanks for the link. Looks like we don't have to have it, as we don't have multiple graphs and aren't referring to the graph as a whole. As you say, rdflib does the serialisation and doesn't add it in. But we can always pick it up later if we feel it would be more correct.
