### ISSUE TITLE
As a developer, I want to test creating triples from the new DAAN OAI-PMH

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#54]
Currently, we import our Linked Data from OAI for the iMMIx database. There is now an OAI-PMH available for DAAN. We need to adjust the beng-lod-server code to use the new OAI-PMH, and compare this with the alternative option of getting triples from the backbone importer (See [LOD pipelines](https://github.com/beeldengeluid/beng-lod-server/wiki/LOD-pipeline))

**Tasks**
- [x] Create a branch of the beng-lod-server
- [ ] Adapt the XSLT mapping to the DAAN data and the new NISV DAAN RDF schema

**Acceptance criteria**
- Unit tests are passed for creating triples for series, seasons, programmes and clips
- The generated triples are in accordance with the NISV schema

The triples will NOT be loaded to a triplestore, that is a separate step in the pipeline that Willem Melder is already developing.

**Comment by mwigham** [comment]
This issue is ready for review. I have used a different approach to the XSLT, instead transforming the XML to json and then using schema information to convert it to RDF. I chose this option as it allows us to use the schema as a central point for defining the conversion, as we can then parameterise code for similar data types programmatically, and as the data format in the DAAN OAI-PMH is very close to the json format used in the backbone, allowing easy conversion. 

@wmelder can you review please? 
Test plan:
- [ ] Check out branch daan-oai-to-rdf from beng-lod-server, and check that all the unit tests run ok
- [ ] Run the beng-lod-server locally, and try it out with at least one item of each level (series, season etc.). You can get test identifiers from the OAI-PMH (e.g. http://acc-app-bng-01.beeldengeluid.nl:8103/oai?verb=ListRecords&MetadataPrefix=fe&set=LOGTRACKITEM). When testing with a logtrack item, make sure you choose one that has logtrack_type scene description
-  [ ] Check that the metadata is complete and correct for your test items. You can compare it with the metadata in the OAI-PMH (e.g. http://acc-app-bng-01.beeldengeluid.nl:8103/oai?verb=GetRecord&MetadataPrefix=fe&identifier=oai:LOGTRACKITEM:2101909180736618724)
- [ ] Try some incorrect input - wrong level for the identifier, non-existing identifier etc. - and see if the server handles it ok

Not all the OAI-PMH metadata is converted to RDF. In particular mdissues, sourcedescription, publishings, ipr and aclgroups are not modelled, so you can ignore all these. If a field is missing in the RDF, then you can check if it should be present by looking it up in [this spreadsheet](https://docs.google.com/spreadsheets/d/15rP7aMZj5nTrf8WFmBTgBwSIoobM7t3febRGse6rHAg/edit#gid=1100180947). Search for the DAAN field name and see if an RDF concept is filled in in column H. If so, then it should be present in the RDF data.

Two bugs I have already noticed (but which are not directly solvable so will need to be in a new issue) are:
- Sometimes recording information fields are not bundled under 'recordinginformation', but included as single fields. They are then not picked up by the RDF transformation. I need to check if this is the intended behaviour in OAI-PMH
- The title type is missing for main titles. This is because title text and title type are not bundled together, but are separate fields. Any ideas as to how to handle this are welcome!

Thanks in advance.

**Comment by wmelder** [comment]
@mwigham [here](https://docs.google.com/document/d/1MoVf-C3Rmu4XrPtMn0xem3J9wydXFRlzacrx7m074DM/edit?usp=sharing) are some comments..

**Comment by mwigham** [comment]
@wmelder Thank you very much for the thorough review. I've added some reactions, for the rest I will work through the points and implement them.

**Comment by wmelder** [comment]
@mwigham @jblom 

Can we discuss this branch? It is functionally doing what it should right now, but it could use a more object oriented approach. Class members are now manipulated by separate functions from other packages... It might be difficult to maintain....

**Comment by mwigham** [comment]
@wmelder Yes, fine to discuss it, it's good that you keep an eye out for this sort of thing.

**Comment by wmelder** [comment]
@mwigham Hi Mari, it took some time to commit the branch wm_daan_oai2rdf with the object oriented example code. Please check it out and use it for your classes. It is just an example of how to make the data (member) part of the class (object) and only allow class functions (with the _-underscore starting name) to manage that data. I also added a very basic initialization of the DAANClassesImporter in the DAANLODHandler, so that you can see how to include it in the main object. I don't mean to interfere too much in your coding, but I felt the OO principles were missing and these are important to make your code more manageable and shareable. Good luck!

**Comment by mwigham** [comment]
@wmelder Thank you very much for the refactored code, it's great. I have incorporated your changes and they also inspired me to tidy up some of the rest of the code. I have merged it into daan-oai-to-rdf. Please take a look and see if it's ok. In the meantime I'll move on to the rest of your comments.

**Comment by mwigham** [comment]
@wmelder I've adapted the code according to your comments, please look and see if they have been addressed now.

**Comment by wmelder** [comment]
@mwigham I added the class loading the the __init__, so it doesn't have to load the schema and properties every time a request is arriving... could you please check ?

**Comment by mwigham** [comment]
in which init? I'm afraid I seem to be overlooking it in the code

**Comment by mwigham** [comment]
@wmelder Can I suggest we close this issue and look at loading the schema in the init in a separate one? As that is more an improvement than a correction.

**Comment by wmelder** [comment]
@mwigham that's fine with me. Close this one and create a new issue for the loading? Can you create a pull request and assign me as reviewer when you're ready?

**Comment by mwigham** [comment]
@wmelder. Yes, I'll do that

**Comment by mwigham** [comment]
Loading will be tackled in #66
