### ISSUE TITLE
EPIC: Use Linked Data to enable enriching/linking Media Suite collections with external collections

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#56]
There are many external linked data collections that can supply relevant information for Media Suite users. Some of these are other heritage collections, such as KB linked data, others are broader, such as wikidata.

This epic includes tasks such as:
- [ ] Identifying relevant sources
- [ ] Aligning schemas for Media Suite collections to external schemas
- [ ] Importing data into the Media Suite

Tasks involving the use of the external data, e.g. advanced search functionality using information from wikidata, should be included in another epic.

**Comment by mwigham** [comment]
@wmelder @jblom I have proposed this epic to cover the more long-term linked data development that what is necessary for the immediate DAAN pipeline and Linked Data sandbox. This way we have a home for work that is already in progress on these sort of issues, such as that related to the DERA demo, that will benefit the Media Suite in the later stages of linked data implementation.

**Comment by mwigham** [comment]
This epic won't have high priority, but it involves work that takes a long time and so it is good to get the ball rolling.
