### ISSUE TITLE
EPIC: As developer I need to create a small app with GTAA/Persons and Wikidata to show LOD added value

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#77]
## Context
Within Clariah more datasets need to be connected, so that the goals for the whole clariah program are met. More cross collection search.

To start of, we can create some 'micro'-apps that show some of the benefits and some of the scenarios where interlinked data has added value. Primarily, these use cases will be organised around the entities that are typically present in every individual dataset: persons, places, event, subjects... Mostly, these are not present in the metadata in a way that cross datasets matches are possible. So creating links between the entities in itself is already a good step in making the datasets interconnected.

## Use case
Use the GTAA/Personen dataset and integrate the information from wikidata in a simple app. Use role properties to filter the NISV catalogue for the persons found. Add more datasets like RKDartist or Clariah person datasets (maybe KB thesaurus for author names?)

## Todo's
- [x] Create app using Flask and Vue JS
- [x] Create app using flask, Jinja2 and Bootstrap.js
- [x] Prepare the SPARQL queries for GTAA/Person and Wikidata
- [x] Present the results showing all information user friendly (either the data is overlapping or complementary)
- [x] Present a list of roles in which a person is present in the catalogue data
- [x] Filter the catalogue results with the role information in the previous step

## Acceptance criteria
- [x] present demo
- [x] list of lessons learned and paragraph for future work

**Comment by wmelder** [comment]
flask/vue.js and chrome give CORS problems.
now continue with flask/jinja2/bootstrap

**Comment by jblom** [comment]
@wmelder can you please let us know what you want to do with this epic? Does it require a review?

**Comment by wmelder** [comment]
- besproken met Mari en Roeland
- demo komt aan bod tijdens LOD workshop
- zie lessons learned above

**Comment by jblom** [comment]
@wmelder nice!
