### ISSUE TITLE
EPIC: Enable Media Suite users to filter data based on politics properties

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#80]
Politicus browser:

Het doel van een politicus browser is om het makkelijker te maken om politiek-getinte materiaal te vinden of analyseren in de Media Suite. Wij hebben geen informatie over politici in de Media Suite, maar de GTAA en WikiData geven wel aan wie een politicus is, welke partij hij lid van is enz. Deze informatie kunnen we gebruiken om Media Suite users het makkelijker te maken. Zo kan de gebruiker vanuit zijn interessegebied rondom de politicus het archief benaderen.

- [x] create app in flask
- [x] create initial HTML page with search bar
- [x] create a model for the app data (JSON)
- [x] link the search bar to the GTAA queries
- [x] create the wikidata queries in grlc (NOTE: [query limits](https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Query_limits))
- [x] create the nisv cat queries in grlc
- [x] fill the model with the result data from the queries
- [x] build an HTML template for the results
- [x] build a tagcloud given the subject information
- [x] OPTIONAL show the political aligment in a spectrum
- [x] report on the usability 
- [x] discuss integration issues for the Media Suite

----------------------------------------------
This comes from the inspiration document

Er zijn twee mogelijke varianten hiervan:

* Zoeken: Gebruik de wikidata API en GTAA om politici op te zoeken op basis van een beperkt aantal criteria zoals naam, ideologie, geslacht, politiek partij enz. Zoek dan items op in ons archief waarin deze mensen voorkomen. Een tussenstap hierbij is te laten zien aan welke onderwerpen in het archief de persoon gerelateerd is. Tevens kan de rol waarin hij/zij voorkomt in dit materiaal als selectiemogelijkheid geboden worden. Het type van de media objecten kan ook als filter/facet gebruikt worden.

* Analyseren: Doe een eenvoudige search via the Search API (misschien alleen zoeken op trefwoorden, om UI kant beperkt te houden). Voor de mensen in deze set zoekresultaten, importeer de informatie over bijv. Ideologie via de wikidata API, en gebruik dit om een analyse te doen van een set zoekresultaten, bijv. Hoe is de verdeling over ideologie?

* Use cases: Linking with WikiData to define more advanced search queries for people; Linking with WikiData to analyse the results of search queries for people

* Infrastructuur stappen: Linked Data with grlc API , Use grlc for wikidata queries.

**Comment by mwigham** [comment]
Ideas for future extension to the political functionality are:
- use speaker labels or face labels to allow distribution over speaker time, screen time
- save the data to the index, allowing political facets in the Media Suite
- use in combination with topics

**Comment by mwigham** [comment]
@wmelder do you think we can close this epic? I think we have achieved very nice results which we will take forward in new epics

**Comment by wmelder** [comment]
@mwigham I think we can close it.
